# Generated by Django 3.2.25 on 2024-04-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Words_file', models.FileField(upload_to='Corpus/Listening/Words/')),
                ('Src_file', models.FileField(upload_to='Corpus/Listening/File/')),
                ('Create_time', models.DateTimeField(auto_now_add=True)),
                ('Update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
