# Generated by Django 3.2.25 on 2024-03-30 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Speaking', '0002_auto_20240330_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ielts1',
            old_name='Topic_id',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='ielts2',
            old_name='Topic_id',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='ielts3',
            old_name='Topic_id',
            new_name='Topic',
        ),
    ]
