# Generated by Django 3.2.25 on 2024-04-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Speaking', '0003_auto_20240330_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ielts1',
            name='Question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ielts2',
            name='Question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ielts2',
            name='Requirement',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ielts3',
            name='Question',
            field=models.CharField(max_length=500),
        ),
    ]
