# Generated by Django 3.2.25 on 2024-04-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Speaking', '0004_auto_20240407_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='ielts1',
            name='Intro_scr_file',
            field=models.FileField(null=True, upload_to='Corpus/IELTS1/introduce/'),
        ),
        migrations.AddField(
            model_name='ielts1',
            name='Src_file',
            field=models.FileField(null=True, upload_to='Corpus/IELTS1/file/'),
        ),
        migrations.AddField(
            model_name='ielts2',
            name='Intro_scr_file',
            field=models.FileField(null=True, upload_to='Corpus/IELTS2/introduce/'),
        ),
        migrations.AddField(
            model_name='ielts2',
            name='Src_file',
            field=models.FileField(null=True, upload_to='Corpus/IELTS2/file/'),
        ),
        migrations.AddField(
            model_name='ielts3',
            name='Intro_scr_file',
            field=models.FileField(null=True, upload_to='Corpus/IELTS3/introduce/'),
        ),
        migrations.AddField(
            model_name='ielts3',
            name='Src_file',
            field=models.FileField(null=True, upload_to='Corpus/IELTS3/file/'),
        ),
    ]
