# Generated by Django 3.2.25 on 2024-04-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Listening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Listening_Corpus_list', models.CharField(max_length=1000)),
                ('Listening_Last_MyDictation', models.CharField(max_length=1000)),
                ('Listening_Last_MyCorpusBreak', models.IntegerField(default=0)),
                ('Create_time', models.DateTimeField(auto_now_add=True)),
                ('Update_time', models.DateTimeField(auto_now=True)),
                ('Listening_Last_MyCorpusID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Listening.corpus')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Create_time', models.DateTimeField(auto_now_add=True)),
                ('Update_time', models.DateTimeField(auto_now=True)),
                ('MyDictation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.listening')),
            ],
        ),
    ]
